// Serategna Job Taxonomy — trilingual (EN · አማርኛ Ge'ez+translit · Afaan Oromoo Qubee).
// Work-type tags: F=Formal, I=Informal, G=Gig/on-demand, S=Short-run/part-time.
// 20 groups → roles. Each group maps to a pricing category + icon + vertical so
// price bands, icons and matching keep working across the whole taxonomy.

export interface Role {
  k: string; // stable key (search/index)
  en: string;
  am: string; // Ge'ez script + (transliteration)
  om: string; // Qubee
  t: string; // tags subset of FIGS
}

export interface TaxonomyGroup {
  key: string;
  en: string;
  am: string;
  om: string;
  icon: string;
  vertical: 'home' | 'delivery' | 'pro' | 'care';
  bandLow: number;
  bandHigh: number;
  roles: Role[];
}

export const TAXONOMY: TaxonomyGroup[] = [
  {
    key: 'delivery_logistics', en: 'Delivery & Logistics', am: 'ማድረስና ሎጂስቲክስ', om: 'Geejjibaa fi Lojistiksii', icon: 'package', vertical: 'delivery', bandLow: 100, bandHigh: 1500,
    roles: [
      { k: 'moto_rider', en: 'Motorbike delivery rider', am: 'የሞተር ሳይክል ዕቃ አድራሽ (Yemotor Saykil Eqa Adrash)', om: 'Geessituu Meeshaa Mootoraa', t: 'GI' },
      { k: 'bicycle_courier', en: 'Bicycle courier', am: 'የብስክሌት መልዕክተኛ (Yebisiklet Mel\'ektegna)', om: 'Ergaa Geessituu Saayikilii', t: 'GI' },
      { k: 'car_delivery', en: 'Car delivery driver', am: 'የመኪና ዕቃ አከፋፋይ (Yemekina Eqa Akefafay)', om: 'Konkolaachisaa Geessitootaa', t: 'G' },
      { k: 'bajaj_delivery', en: 'Three-wheeler (Bajaj) delivery', am: 'የባጃጅ ዕቃ ማመላለሻ (Yebajaj Eqa Mamelalesha)', om: 'Geessituu Meeshaa Baajajii', t: 'GI' },
      { k: 'truck_light', en: 'Truck driver — light cargo', am: 'የቀሊል ጭነት መኪና ሹፌር (Yeqelil Chinet Mekina Shufer)', om: 'Konkolaachisaa Fe\'umsa Salphaa', t: 'FG' },
      { k: 'truck_heavy', en: 'Truck driver — heavy/long-haul', am: 'የከባድ ጭነት መኪና ሹፌር (Yekebad Chinet Mekina Shufer)', om: 'Konkolaachisaa Fe\'umsa Cimaa', t: 'F' },
      { k: 'food_rider', en: 'Food delivery rider', am: 'የምግብ አድራሽ (Yemigib Adrash)', om: 'Geessituu Nyaataa', t: 'G' },
      { k: 'grocery_shopper', en: 'Grocery shopper & delivery', am: 'የሸቀጣሸቀጥ ገዢና አድራሽ (Yesheqetasheqet Gezina Adrash)', om: 'Bitataa fi Geessituu Shakaallii', t: 'GS' },
      { k: 'parcel_sorter', en: 'Parcel sorter', am: 'የፖስታ/ፓኬጅ ለዪ (Yeposta/Package Leyi)', om: 'Addaan Baastuu Paakeejii', t: 'IS' },
      { k: 'warehouse_loader', en: 'Warehouse loader/unloader', am: 'የዕቃ ጫኝና አራጋፊ (Yeeqa Chagnena Aragafi)', om: 'Hojjetaa Fe\'umsaafi Buusi Mana Kuusaa', t: 'IS' },
      { k: 'inventory_clerk', en: 'Inventory stock clerk', am: 'የክምችት ተቆጣጣሪ ፀሐፊ (Yekimchit Teqotatari Tsehafi)', om: 'Galmeessaa Kuusaa Meeshaa', t: 'FI' },
      { k: 'last_mile', en: 'Last-mile dispatch coordinator', am: 'የመጨረሻ ምዕራፍ ዕቃ ስርጭት አስተባባሪ (Yemechersha Mi\'iraf Eqa Sirchit Astebabari)', om: 'Qindeessaa Ergaa Xumuraa', t: 'F' },
      { k: 'moving_helper', en: 'Moving & relocation helper', am: 'የቤት ዕቃ ማዘዋወር ረዳት (Yebet Eqa Mazewawer Redat)', om: 'Gargaaraa Meeshaa Manaa Geeddarachuu', t: 'IS' },
      { k: 'furniture_mover', en: 'Furniture mover', am: 'የቤት ዕቃ አዘዋዋሪ (Yebet Eqa Azewawari)', om: 'Geessituu Meeshaalee Manaa', t: 'IS' },
      { k: 'water_delivery', en: 'Water delivery (jerrycan/tanker)', am: 'የውሃ አከፋፋይ (Yewuha Akefafay)', om: 'Raabsituu Bishanii', t: 'IG' },
      { k: 'gas_delivery', en: 'Gas cylinder delivery', am: 'የጋዝ ሲሊንደር አድራሽ (Yegaz Cylinder Adrash)', om: 'Geessituu Siliindara Gaasii', t: 'IG' },
    ],
  },
  {
    key: 'driving_transport', en: 'Driving & Transport', am: 'መንዳትና ትራንስፖርት', om: 'Konkolaachisuu fi Geejjibaa', icon: 'car', vertical: 'delivery', bandLow: 200, bandHigh: 3000,
    roles: [
      { k: 'taxi_driver', en: 'Taxi driver (ride-hail)', am: 'የራይድ/ታክሲ አሽከርካሪ (Yeride/Taxi Ashkerkari)', om: 'Konkolaachisaa Taaksii (Kooba/Feres)', t: 'G' },
      { k: 'private_driver', en: 'Private/personal driver (chauffeur)', am: 'የግል ረዳት አሽከርካሪ (Yegil Redat Ashkerkari)', om: 'Konkolaachisaa Dhuunfaa', t: 'FI' },
      { k: 'minibus_driver', en: 'Minibus (Wiyiyit) driver', am: 'የሚኒባስ አሽከርካሪ (Yeminibus Ashkerkari)', om: 'Konkolaachisaa Miniibaasii', t: 'I' },
      { k: 'weyala', en: 'Minibus taxi conductor (Weyala)', am: 'ታክሲ ረዳት / ወያላ (Taxi Redat / Weyala)', om: 'Gargaaraa Taaksii (Weeyyaalaa)', t: 'IS' },
      { k: 'bus_driver', en: 'Bus driver', am: 'የአውቶቡስ አሽከርካሪ (Yeautobus Ashkerkari)', om: 'Konkolaachisaa Otoobisii', t: 'F' },
      { k: 'school_run', en: 'School run driver', am: 'የትምህርት ቤት ሰርቪስ አሽከርካሪ (Yetimihirt Bet Service Ashkerkari)', om: 'Konkolaachisaa Barattootaa', t: 'FS' },
      { k: 'tour_driver', en: 'Tour/shuttle driver', am: 'የቱሪስት አሽከርካሪ (Yetourist Ashkerkari)', om: 'Konkolaachisaa Daawwattootaa', t: 'FG' },
      { k: 'ambulance_driver', en: 'Ambulance driver', am: 'የአምቡላንስ አሽከርካሪ (Yeambulance Ashkerkari)', om: 'Konkolaachisaa Ambuulaansii', t: 'F' },
      { k: 'forklift_op', en: 'Forklift operator', am: 'ፎርክሊፍት አንቀሳቃሽ (Forklift Anqesaqash)', om: 'Opreitara Forkliiftii', t: 'F' },
      { k: 'tractor_op', en: 'Tractor operator', am: 'የትራክተር አሽከርካሪ (Yetractor Ashkerkari)', om: 'Opreitara Tiraakterii', t: 'IS' },
      { k: 'heavy_machine_op', en: 'Heavy machinery operator', am: 'የከባድ ማሽነሪ አንቀሳቃሽ (Yekebad Machinery Anqesaqash)', om: 'Opreitara Maashinii Cimaa', t: 'F' },
      { k: 'night_driver', en: 'Designated/late-night driver', am: 'የሌሊት ተለዋጭ አሽከርካሪ (Yelelit Telewach Ashkerkari)', om: 'Konkolaachisaa Halkanii Geeddaramaa', t: 'GS' },
    ],
  },
  {
    key: 'home_cleaning', en: 'Home & Cleaning Services', am: 'የቤትና ጽዳት አገልግሎት', om: 'Tajaajila Manaa fi Qulqullinaa', icon: 'sparkles', vertical: 'home', bandLow: 200, bandHigh: 1200,
    roles: [
      { k: 'house_cleaner', en: 'House cleaner', am: 'የቤት ጽዳት ሰራተኛ (Yebet Tsidat Serategna)', om: 'Hojjattuu Qulqullina Manaa', t: 'IGS' },
      { k: 'deep_clean', en: 'Deep-cleaning specialist', am: 'የጥልቅ ጽዳት ባለሙያ (Yetilq Tsidat Balemuya)', om: 'Ogeessa Qulqullina Cimaa', t: 'GS' },
      { k: 'office_cleaner', en: 'Office/commercial cleaner', am: 'የቢሮ ጽዳት ሰራተኛ (Yebiro Tsidat Serategna)', om: 'Qulqulleessituu Waajiraa', t: 'FI' },
      { k: 'laundry_iron', en: 'Laundry & ironing', am: 'አልባሳት አጣቢና ተኳሽ (Albasat Atabina Tekuash)', om: 'Miictuu fi Koomtuu Uffataa', t: 'IG' },
      { k: 'window_cleaner', en: 'Window cleaner', am: 'የመስኮት ጽዳት ሰራተኛ (Yemeskot Tsidat Serategna)', om: 'Qulqulleessituu Foddaa', t: 'IS' },
      { k: 'carpet_sofa', en: 'Carpet & sofa cleaning', am: 'የምንጣፍና ሶፋ አጣቢ (Yemintafena Sofa Atabi)', om: 'Qulqulleessituu Afataa fi Sifaa', t: 'GS' },
      { k: 'post_construction', en: 'Post-construction cleanup', am: 'ከግንባታ በኋላ ማጽጃ ሰራተኛ (Ke-ginbata Behuala Matsja Serategna)', om: 'Qulqulleessituu Ijaarsa Boodaa', t: 'IS' },
      { k: 'live_in_keeper', en: 'Live-in housekeeper', am: 'አዳሪ የቤት ሰራተኛ (Adari Yebet Serategna)', om: 'Hojjattuu Manaa Bultii', t: 'FI' },
      { k: 'day_keeper', en: 'Day housekeeper', am: 'የቀን የቤት ሰራተኛ (Yeqen Yebet Serategna)', om: 'Hojjattuu Manaa Guyyaa', t: 'IS' },
      { k: 'dishwasher', en: 'Dishwasher (events/restaurant)', am: 'ሰህን አጣቢ (Sehin Atabi)', om: 'Miictuu Saanii', t: 'IS' },
      { k: 'gardener', en: 'Gardener / landscaper', am: 'የአትክልት ቦታ ሰራተኛ (Yeatikilt Bota Serategna)', om: 'Kunuunsituu Masiinaa / Atilmaan', t: 'IGS' },
      { k: 'pool_clean', en: 'Pool cleaning & maintenance', am: 'የዋና ገንዳ ማጽጃና ጥገና ባለሙያ (Yewana Genda Matsjana Tgena Balemuya)', om: 'Qulqulleessituu fi Suphituu Dirree Daakaa', t: 'GS' },
      { k: 'pest_control', en: 'Pest control technician', am: 'የነፍሳትና ወረርሽኝ መከላከያ ቴክኒሻን (Yenefsatina Werershign Mekelekeya Technician)', om: 'Teekinishiana To\'annoo Farra Raammottaa', t: 'FG' },
      { k: 'waste_recycle', en: 'Waste collection / recycling', am: 'የቆሻሻ ሰብሳቢ / ቆራሊዮ (Yeqoshasha Sabsabi / Qoralyo)', om: 'Sassaabduu Balfaa / Qoraaliyoo', t: 'IF' },
    ],
  },
  {
    key: 'skilled_construction', en: 'Skilled Trades & Construction', am: 'የእጅ ሙያና ግንባታ', om: 'Ogummaa Harkaa fi Ijaarsa', icon: 'hammer', vertical: 'home', bandLow: 350, bandHigh: 5000,
    roles: [
      { k: 'mason', en: 'Mason / bricklayer', am: 'ግንበኛ (Ginbegna)', om: 'Jaartuu / Ijaartuu Ginbii', t: 'IF' },
      { k: 'construction_laborer', en: 'Daily-wage construction laborer', am: 'የቀን ግንባታ ሰራተኛ (Yeqen Ginbata Serategna)', om: 'Hojjetaa Guyyaa Ijaarsaa', t: 'IS' },
      { k: 'carpenter', en: 'Carpenter', am: 'አናጺ (Anatsi)', om: 'Anaaxii', t: 'IF' },
      { k: 'furniture_maker', en: 'Furniture maker / joiner', am: 'የእንጨት ውጤቶች ሰሪ (Ye-enchet Witetoch Seriy)', om: 'Tolchituu Meeshaa Manaa (Mukaa)', t: 'IF' },
      { k: 'plumber', en: 'Plumber', am: 'የቧንቧ ባለሙያ (Yebonba Balemuya)', om: 'Ogeessa Boombii Bishanii', t: 'IFG' },
      { k: 'electrician', en: 'Electrician', am: 'የኤሌክትሪክ ባለሙያ (Yeelectric Balemuya)', om: 'Ogeessa Elektiriikii', t: 'IFG' },
      { k: 'welder', en: 'Welder / metal fabricator', am: 'የብረታብረትና ዌልዲንግ ባለሙያ (Yebiretabiretena Welding Balemuya)', om: 'Hojjetaa Sibilootaa fi Waalderii', t: 'IF' },
      { k: 'painter', en: 'Painter (buildings)', am: 'የህንፃ ቀለም ቀቢ (Yehintsa Qelem Qebiy)', om: 'Dibduu Halluu Gamoo', t: 'IGS' },
      { k: 'tiler', en: 'Tiler / floor layer', am: 'የሴራሚክና ንጣፍ ገጣሚ (Yeseramicna Mintaf Getami)', om: 'Afituu Kaaroofii / Tilaa', t: 'IG' },
      { k: 'plasterer', en: 'Plasterer', am: 'የለሰን ሰራተኛ (Lesen Serategna)', om: 'Haadhituu Lallafaa / Laasitii', t: 'IG' },
      { k: 'roofer', en: 'Roofer', am: 'የጣሪያ ቆርቆሮ ገጣሚ (Yetariya Qorqoro Getami)', om: 'Dhaabduu Baaxii Manaa', t: 'IG' },
      { k: 'glass_alu', en: 'Glass & aluminium fitter', am: 'የብርጭቆና አልሙኒየም ገጣሚ (Yeberchiqona Aluminium Getami)', om: 'Naqtuu Daawwitii fi Alumiiniyamii', t: 'IF' },
      { k: 'hvac', en: 'HVAC technician', am: 'የአየር ማቀዝቀዣና ማሞቂያ ቴክኒሻን (Yeayyer Maqezezhana Mamoqiya Technician)', om: 'Teekinishiana Sirna Qilleensaa (HVAC)', t: 'FG' },
      { k: 'scaffolder', en: 'Scaffolder', am: 'የማገር/ባስካላ ገጣሚ (Yemager/Bascala Getami)', om: 'Dhaabduu Muka Ijaarsaa', t: 'IS' },
      { k: 'concrete_rebar', en: 'Concrete/rebar worker', am: 'የፌሮ-ኮንክሪት ሰራተኛ (Yeferro-Concrete Serategna)', om: 'Hojjetaa Sibaalloo fi Konkiriitii', t: 'IS' },
      { k: 'foreman', en: 'Site foreman / supervisor', am: 'የህንፃ ግንባታ ፎርማን (Yehintsa Ginbata Foreman)', om: 'To\'ataa Ijaarsaa (Foormanii)', t: 'F' },
      { k: 'surveyor_asst', en: 'Surveyor assistant', am: 'የልኬት ረዳት ባለሙያ (Yeliket Redat Balemuya)', om: 'Gargaaraa Kaartaa fi Lekeessaa (Sarveeyeraa)', t: 'FS' },
      { k: 'heavy_mechanic', en: 'Heavy-equipment mechanic', am: 'የከባድ ማሽነሪ መካኒክ (Yekebad Machinery Mechanic)', om: 'Mekaanika Maashinii Cimaa', t: 'F' },
      { k: 'stone_cutter', en: 'Stone cutter / quarry worker', am: 'የድንጋይ ቋጥኝ ፈላጭ (Yedengay Quatign Felach)', om: 'Qoraa/Kutaa Dhagaa', t: 'I' },
    ],
  },
  {
    key: 'repairs_technical', en: 'Repairs & Technical', am: 'ጥገናና ቴክኒክ', om: 'Suphaa fi Teekinikaa', icon: 'wrench', vertical: 'home', bandLow: 200, bandHigh: 3000,
    roles: [
      { k: 'phone_repair', en: 'Mobile phone repair', am: 'የሞባይል ስልክ ጥገና ባለሙያ (Yemobile Silk Tgena Balemuya)', om: 'Suphaa Moobaayilii', t: 'IG' },
      { k: 'computer_repair', en: 'Computer / laptop repair', am: 'የኮምፒውተር ጥገና ባለሙያ (Yecomputer Tgena Balemuya)', om: 'Suphaa Kompiutaraa', t: 'IG' },
      { k: 'tv_repair', en: 'TV & electronics repair', am: 'የቲቪና ኤሌክትሮኒክስ ጥገና ባለሙያ (Ye-TV-na Electronics Tgena Balemuya)', om: 'Suphaa Tiivii fi Elektirooniksii', t: 'IG' },
      { k: 'fridge_ac', en: 'Refrigerator/AC repair', am: 'የፍሪጅና አየር ማቀዝቀዣ ጥገና ባለሙያ (Yefridge-na Ayyer Maqezezha Tgena Balemuya)', om: 'Suphaa Maashinii Qoraneessaa', t: 'IG' },
      { k: 'washing_repair', en: 'Washing machine repair', am: 'የልብስ ማጠቢያ ማሽን ጥገና ባለሙያ (Yelibs Matebya Machine Tgena Balemuya)', om: 'Suphaa Maashinii Miiccaa', t: 'G' },
      { k: 'generator_repair', en: 'Generator repair', am: 'የጄነሬተር ጥገና ባለሙያ (Yegenerator Tgena Balemuya)', om: 'Suphaa Jenereetaraa', t: 'IG' },
      { k: 'watch_repair', en: 'Watch/clock repair', am: 'የሰዓት ጥገና ባለሙያ (Yese\'at Tgena Balemuya)', om: 'Suphaa Sa\'aatii', t: 'I' },
      { k: 'cobbler', en: 'Shoe repair (cobbler/Listro)', am: 'ጫማ ጠጋኝና ሊስትሮ (Chama Tegagn-na Listro)', om: 'Suphaa fi Qulqulleessituu Kophee', t: 'I' },
      { k: 'bike_repair', en: 'Bicycle repair', am: 'የብስክሌት ጥገና ባለሙያ (Yebisiklet Tgena Balemuya)', om: 'Suphaa Saayikilii', t: 'IG' },
      { k: 'moto_mechanic', en: 'Motorbike mechanic', am: 'የሞተር ሳይክል መካኒክ (Yemotor Saykil Mechanic)', om: 'Mekaanika Mootoraa', t: 'IG' },
      { k: 'auto_mechanic', en: 'Auto mechanic', am: 'የመኪና መካኒክ (Yemekina Mechanic)', om: 'Mekaanika Konkolaataa', t: 'IFG' },
      { k: 'auto_electrician', en: 'Auto electrician', am: 'የመኪና ኤሌክትሪሻን (Yemekina Electrician)', om: 'Elektiriishinii Konkolaataa', t: 'IF' },
      { k: 'tyre_repair', en: 'Tyre & puncture repair', am: 'የጎማ ጥገና ሰራተኛ (Yegoma Tgena Serategna)', om: 'Suphaa Gomaa Konkolaataa', t: 'IG' },
      { k: 'car_wash', en: 'Car wash attendant', am: 'የመኪና አጣቢ (Yemekina Atabi)', om: 'Dhiqtulee Konkolaataa', t: 'IS' },
      { k: 'locksmith', en: 'Locksmith', am: 'ቁልፍ ጠጋኝና ሰሪ (Yequlf Tegagn-na Seriy)', om: 'Ogeessa Surtuu/Qulfee', t: 'IG' },
      { k: 'solar_installer', en: 'Solar panel installer/technician', am: 'የሶላር ሲስተም ቴክኒሻን (Yesolar System Technician)', om: 'Teekinishiana Humna Aduu', t: 'FG' },
      { k: 'cctv_installer', en: 'CCTV & security system installer', am: 'የሲሲቲቪና የደህንነት ካሜራ ገጣሚ (Ye-CCTV-na Yedehninet Camera Getami)', om: 'Dhaabduu Kaameraa Nageenyaa', t: 'FG' },
      { k: 'dish_installer', en: 'Satellite dish / antenna installer', am: 'የዲሽና አንቴና ገጣሚ (Yedish-na Antenna Getami)', om: 'Dhaabduu Diishii Saateelaayitii', t: 'IG' },
    ],
  },
  {
    key: 'food_hospitality', en: 'Food, Hospitality & Catering', am: 'ምግብ፣ መስተንግዶና ኬተሪንግ', om: 'Nyaataa, Keessummeessuu fi Keeteriingii', icon: 'chef-hat', vertical: 'home', bandLow: 200, bandHigh: 2500,
    roles: [
      { k: 'waiter', en: 'Waiter / waitress', am: 'አስተናጋጅ (Astenagaj)', om: 'Keessummeessituu', t: 'FIS' },
      { k: 'barista', en: 'Barista', am: 'ባሪስታ / የቡና ባለሙያ (Barista / Yebunna Balemuya)', om: 'Baariistaa Bunaa', t: 'FS' },
      { k: 'bartender', en: 'Bartender', am: 'ባርማን (Barman)', om: 'Baartendarii', t: 'FS' },
      { k: 'line_cook', en: 'Line cook', am: 'ረዳት ምግብ አሰናጅ (Redat Migib Asenaj)', om: 'Gargaaraa Qopheessaa Nyaataa', t: 'FI' },
      { k: 'chef', en: 'Chef / head cook', am: 'ዋና ምግብ አሰናጅ / ሼፍ (Wana Migib Asenaj / Chef)', om: 'Muummicha Qopheessaa Nyaataa', t: 'F' },
      { k: 'sous_chef', en: 'Sous chef', am: 'ምክትል ዋና ምግብ አሰናጅ (Mikitil Wana Migib Asenaj)', om: 'Itti-aanaa Qopheessaa Nyaataa', t: 'F' },
      { k: 'baker', en: 'Pastry chef / baker', am: 'ኬክና ዳቦ ጋጋሪ (Cake-na Dabo Gagari)', om: 'Tolchituu Daabboo fi Keekii', t: 'FI' },
      { k: 'kitchen_porter', en: 'Kitchen porter', am: 'የኩሽና ረዳት (Yekushina Redat)', om: 'Gargaaraa Kushiinaa', t: 'IS' },
      { k: 'catering_staff', en: 'Catering staff (events)', am: 'የግብዣ ዝግጅት ምግብ አቅራቢ ሰራተኛ (Yegibzha Zigijit Migib Aqrabi Serategna)', om: 'Keessummeessituu Nyaataa Sagantaalee', t: 'GS' },
      { k: 'private_chef', en: 'Home-cook / private chef', am: 'የግል ቤት ምግብ አሰናጅ (Yegil Bet Migib Asenaj)', om: 'Qopheessituu Nyaataa Dhuunfaa', t: 'IG' },
      { k: 'injera_baker', en: 'Injera baker', am: 'እንጀራ ጋጋሪ (Injera Gagari)', om: 'Tolchituu Biddeenaa (Injeraa)', t: 'IG' },
      { k: 'butcher', en: 'Butcher', am: 'ስጋ ቆራጭ (Siga Qorach)', om: 'Kutaa Foonii', t: 'IF' },
      { k: 'juice_bar', en: 'Juice/smoothie bar attendant', am: 'የጭማቂ ቤት ሰራተኛ (Yechimaqi Bet Serategna)', om: 'Raabsituu Cuunfaa Fuduraalee', t: 'IS' },
      { k: 'coffee_ceremony', en: 'Coffee ceremony host', am: 'የባህል ቡና አፍላጭ (Yebahal Bunna Aflach)', om: 'Qopheessituu Sirna Bunaa', t: 'IGS' },
      { k: 'street_vendor', en: 'Food cart / street vendor', am: 'የመንገድ ላይ ምግብ ሻጭ (Yemenged Lay Migib Shach)', om: 'Daldaltuu Nyaataa Daandii', t: 'I' },
      { k: 'restaurant_cashier', en: 'Restaurant host / cashier', am: 'የሬስቶራንት ገንዘብ ተቀባይ (Yerestaurant Genzeb Teqebay)', om: 'Kashiyeerii Restooraantii', t: 'FS' },
      { k: 'banquet_server', en: 'Banquet / wedding server', am: 'የሰርግና ግብዣ አስተናጋጅ (Yeserg-na Gibzha Astenagaj)', om: 'Keessummeessituu Cidhaa fi Sagantaalee', t: 'GS' },
    ],
  },
  {
    key: 'retail_sales', en: 'Retail, Sales & Commerce', am: 'ችርቻሮ፣ ሽያጭና ንግድ', om: 'Daldala Xixiqqaa, Gurgurtaa fi Daldalaa', icon: 'shopping-bag', vertical: 'pro', bandLow: 150, bandHigh: 2000,
    roles: [
      { k: 'shop_assistant', en: 'Shop assistant / sales clerk', am: 'የሱቅ ረዳት / ሽያጭ ሰራተኛ (Yesuq Redat / Shiyach Serategna)', om: 'Gargaaraa/Hojjetaa Suuqii', t: 'FIS' },
      { k: 'cashier', en: 'Cashier', am: 'ገንዘብ ተቀባይ (Genzeb Teqebay)', om: 'Kashiyeerii / Tiketii', t: 'FS' },
      { k: 'gulit_vendor', en: 'Market stall vendor (Gulit)', am: 'የጉሊት ሻጭ (Yegulit Shach)', om: 'Daldaltuu Gabaa Guliitii', t: 'I' },
      { k: 'merchandiser', en: 'Merchandiser / shelf stocker', am: 'የዕቃ አደራጅና መደርደሪያ ሰሪ (Yeeqa Aderajna Mederderiya Seriy)', om: 'Haadhituu Meeshaa Almooraa', t: 'FS' },
      { k: 'field_sales', en: 'Field sales representative', am: 'የመስክ ሽያጭ ተወካይ (Yemesk Shiyach Tewokay)', om: 'Bakka-bu\'aa Gurgurtaa Dirree', t: 'FG' },
      { k: 'door_sales', en: 'Door-to-door sales agent', am: 'በየቤቱ ተዘዋዋሪ የሽያጭ ወኪል (Beyebetu Tezewawari Yeshiyach Wekil)', om: 'Gurgurtuu Manaa-Manaan Daawwattu', t: 'IG' },
      { k: 'mobile_money_agent', en: 'Mobile money agent (Telebirr)', am: 'የሞባይል ባንኪንግ ወኪል / ቴሌብር (Yemobile Banking Wekil / Telebirr)', om: 'Bakka-bu\'aa Telebirr / CBE Birr', t: 'IF' },
      { k: 'airtime_reseller', en: 'Airtime & SIM reseller', am: 'የስልክ ካርድና ሲም ካርድ ሻጭ (Yesilk Card-na SIM Card Shach)', om: 'Gurgurtuu Kaardii fi SIM-ii', t: 'I' },
      { k: 'boutique', en: 'Boutique / fashion retail', am: 'የልብስ ቡቲክ ሽያጭ ሰራተኛ (Yelibs Boutique Shiyach Serategna)', om: 'Hojjattuu Buutiikii Uffataa', t: 'FS' },
      { k: 'pharmacy_sales', en: 'Pharmacy sales assistant', am: 'የመድሃኒት ቤት ሽያጭ ረዳት (Yemedhanit Bet Shiyach Redat)', om: 'Gargaaraa Gurgurtaa Faarmasii', t: 'F' },
      { k: 'hardware_shop', en: 'Hardware shop attendant', am: 'የሃርድዌር/የግንባታ ዕቃ ሱቅ ሰራተኛ (Yehardware Suq Serategna)', om: 'Hojjetaa Suuqii Haardweerii', t: 'FI' },
      { k: 'wholesale_agent', en: 'Wholesale distributor agent', am: 'የጅምላ አከፋፋይ ወኪል (Yejimla Akefafay Wekil)', om: 'Bakka-bu\'aa Raabsaa Jimmilaa', t: 'FG' },
      { k: 'promoter', en: 'Product demonstrator / promoter', am: 'ምርት አስተዋዋቂ / ፕሮሞተር (Mirt Astewawaqi / Promoter)', om: 'Beeksiftuu Oomishaa / Promooteerii', t: 'GS' },
      { k: 'visual_merch', en: 'Visual merchandiser', am: 'የዕቃዎች አቀራረብ ዲዛይነር (Yeeqaoch Aqerareb Designer)', om: 'Bareessituu Mul\'ata Oomishaa', t: 'FG' },
    ],
  },
  {
    key: 'care_domestic', en: 'Care & Domestic', am: 'እንክብካቤና የቤት ውስጥ', om: 'Kunuunsaa fi Mana Keessaa', icon: 'baby', vertical: 'care', bandLow: 200, bandHigh: 1500,
    roles: [
      { k: 'nanny', en: 'Nanny / childminder', am: 'ሞግዚት / የልጅ አስታማሚ (Mogzit / Yelij Astamami)', om: 'Gargaaraa Daaimanii (Haadha Daadhii)', t: 'IFS' },
      { k: 'babysitter', en: 'Babysitter (occasional)', am: 'የትርፍ ሰዓት የልጅ ጠባቂ (Yetirf Se\'at Yelij Tabaqi)', om: 'Tiksituu Daaimanii yeroo gabaabaa', t: 'GS' },
      { k: 'elderly_care', en: 'Elderly caregiver', am: 'የአረጋውያን አስታማሚ (Yearegawiyan Astamami)', om: 'Kunuunsituu Maangaddootaa', t: 'IF' },
      { k: 'live_in_care', en: 'Live-in caregiver', am: 'አዳሪ አስታማሚ / ጠባቂ (Adari Astamami / Tabaqi)', om: 'Kunuunsituu Mana bultii', t: 'FI' },
      { k: 'patient_attendant', en: 'Patient attendant (home)', am: 'የቤት አስታማሚ (Yebet Astamami)', om: 'Kunuunsituu Dhukkubsataa Manaa', t: 'IG' },
      { k: 'special_needs', en: 'Special-needs support worker', am: 'የልዩ ፍላጎት ድጋፍ ሰጪ ባለሙያ (Yeliyu Filagot Digaf Sechi Balemuya)', om: 'Hojjetaa Gargaarsa Fedhii Addaa', t: 'FG' },
      { k: 'postnatal_care', en: 'Postnatal / newborn care', am: 'ያራስና አዲስ የተወለደ ህጻን አስታማሚ (Yarasna Addis Yetewolede Hitsan Astamami)', om: 'Kunuunsituu Deessee fi Mucaa Haarawaa', t: 'IG' },
      { k: 'pet_sitter', en: 'Pet sitter / dog walker', am: 'የቤት እንስሳት ጠባቂና አዘዋዋሪ (Yebet Ensisat Tabaqi-na Azewawari)', om: 'Tiksituu fi Deessiftuu Beeyilada Manaa', t: 'GS' },
      { k: 'house_sitter', en: 'House sitter', am: 'ቤት ጠባቂ ሰራተኛ (Bet Tabaqi Serategna)', om: 'Eegduu Manaa yeroo boqonnaa', t: 'GS' },
      { k: 'personal_assistant', en: 'Personal assistant (household)', am: 'የግል ረዳት ሰራተኛ (Yegil Redat Serategna)', om: 'Gargaaraa Dhuunfaa Manaa', t: 'FI' },
      { k: 'household_cook', en: 'Cook for household', am: 'የቤት ውስጥ ምግብ አሰናጅ (Yebet Wust Migib Asenaj)', om: 'Qopheessituu Nyaataa Manaa', t: 'IF' },
    ],
  },
  {
    key: 'beauty_wellness', en: 'Beauty, Wellness & Personal Care', am: 'ውበት፣ ጤንነትና የግል እንክብካቤ', om: 'Miidhagina, Fayyaa fi Kunuunsa Dhuunfaa', icon: 'scissors', vertical: 'care', bandLow: 150, bandHigh: 2500,
    roles: [
      { k: 'hairdresser', en: 'Hairdresser / stylist', am: 'የሴቶች ፀጉር ስራ ባለሙያ (Yesetoch Tsigur Sira Balemuya)', om: 'Dhaddahituu Rifeensaa Dubartootaa', t: 'IFG' },
      { k: 'barber', en: 'Barber', am: 'የወንዶች ፀጉር አስተካካይ (Yewondoch Tsigur Astekakay)', om: 'Haadduu Rifeensaa Dhiiraa', t: 'IFG' },
      { k: 'makeup_artist', en: 'Makeup artist', am: 'የፊት ውበት ባለሙያ / ሜካፕ (Yefit Wubet Balemuya / Makeup)', om: 'Ogeessaa Miidhassituu Fuulaa', t: 'GS' },
      { k: 'nail_tech', en: 'Nail technician', am: 'የጥፍር ውበት ባለሙያ (Yetifir Wubet Balemuya)', om: 'Miidhassituu Qeensaa', t: 'IG' },
      { k: 'beautician', en: 'Beautician / esthetician', am: 'የቆዳና የፊት ውበት ባለሙያ (Yeqodana Yefit Wubet Balemuya)', om: 'Ogeessaa Miidhassituu Gogaa fi Fuulaa', t: 'IF' },
      { k: 'massage', en: 'Massage therapist', am: 'ማሳጅ ባለሙያ (Massage Balemuya)', om: 'Ogeessa Maasaajii', t: 'FG' },
      { k: 'spa_attendant', en: 'Spa attendant', am: 'የስፓ ሰራተኛ (Yespa Serategna)', om: 'Tajaajiltuu Isppaa', t: 'FS' },
      { k: 'henna_artist', en: 'Henna artist', am: 'የህና ማስተካከያ ባለሙያ (Yehenna Mastekakeya Balemuya)', om: 'Barreessituu Hiinaa', t: 'GS' },
      { k: 'mobile_salon', en: 'Mobile salon (home visits)', am: 'ተንቀሳቃሽ የውበት ሳሎን ሰራተኛ (Tenqesaqash Yewubet Salon Serategna)', om: 'Tajaajiltuu Miidhagina Mana Daawwattu', t: 'GI' },
      { k: 'bridal_stylist', en: 'Bridal stylist', am: 'የሙሽራ ውበት አሰናጅ (Yemushra Wubet Asenaj)', om: 'Qopheessituu Miidhagina Mushurroo', t: 'GS' },
      { k: 'fitness_trainer', en: 'Personal fitness trainer', am: 'የግል ስፖርት አሰልጣኝ (Yegil Sport Aseltagn)', om: 'Leenjisaa Ispoortii Dhuunfaa', t: 'FGS' },
      { k: 'yoga_instructor', en: 'Yoga / pilates instructor', am: 'የዮጋ አሰልጣኝ (Yeyoga Aseltagn)', om: 'Leenjisaa Yoogaa', t: 'GS' },
      { k: 'sports_coach', en: 'Sports coach', am: 'የስፖርት ኮች (Yesport Coach)', om: 'Leenjisaa Ispoortii (Koochii)', t: 'FGS' },
    ],
  },
  {
    key: 'health_medical', en: 'Health & Medical', am: 'ጤናና ህክምና', om: 'Fayyaa fi Yaalaa', icon: 'stethoscope', vertical: 'pro', bandLow: 300, bandHigh: 6000,
    roles: [
      { k: 'nurse', en: 'Nurse (registered)', am: 'ተመዝጋቢ ነርስ (Temezgabi Nurse)', om: 'Lamiessa/Narsi Galmeeffame', t: 'F' },
      { k: 'nursing_aide', en: 'Nursing assistant / aide', am: 'ረዳት ነርስ (Redat Nurse)', om: 'Gargaaraa Narsii (Lamiessaa)', t: 'FI' },
      { k: 'midwife', en: 'Midwife', am: 'አዋላጅ ነርስ (Awalaj Nurse)', om: 'Deessiftuu (Og-deessiftuu)', t: 'F' },
      { k: 'health_extension', en: 'Health extension worker', am: 'የጤና ኤክስቴንሽን ሰራተኛ (Yetena Extension Serategna)', om: 'Hojjetaa Eksiteenshinii Fayyaa', t: 'F' },
      { k: 'pharmacist', en: 'Pharmacist', am: 'ፋርማሲስት (Pharmacist)', om: 'Faarmasiistii', t: 'F' },
      { k: 'pharmacy_tech', en: 'Pharmacy technician', am: 'የፋርማሲ ቴክኒሻን (Yepharmacy Technician)', om: 'Teekinishiana Faarmasii', t: 'F' },
      { k: 'lab_tech', en: 'Lab technician', am: 'የላብራቶሪ ቴክኒሻን (Yelaboratory Technician)', om: 'Teekinishiana Laaboratoorii', t: 'F' },
      { k: 'radiographer', en: 'Radiographer', am: 'የራጅ ባለሙያ (Yeraj Balemuya)', om: 'Ogeessa Raajii', t: 'F' },
      { k: 'physiotherapist', en: 'Physiotherapist', am: 'የፊዚዮቴራፒ ባለሙያ (Yephysiotherapy Balemuya)', om: 'Ogeessa Fiiziyooterappii', t: 'FG' },
      { k: 'dental_assistant', en: 'Dental assistant', am: 'የጥርስ ህክምና ረዳት (Yetirs Hikmina Redat)', om: 'Gargaaraa Yaala Ilkaanii', t: 'F' },
      { k: 'medical_receptionist', en: 'Medical receptionist', am: 'የህክምና ተቀባይ ባለሙያ (Yehikmina Teqebay Balemuya)', om: 'Simattu Waajira Yaalaa', t: 'FS' },
      { k: 'health_volunteer', en: 'Community health volunteer', am: 'የማህበረሰብ ጤና በጎ ፈቃደኛ (Yemahbereseb Tena Bego Feqadegna)', om: 'Fedha-laulaa Fayyaa Hawaasaa', t: 'IS' },
      { k: 'home_health_aide', en: 'Home health aide', am: 'የቤት ውስጥ የጤና ረዳት (Yebet Wust Yetena Redat)', om: 'Gargaaraa Fayyaa Manaa', t: 'IG' },
      { k: 'vet_assistant', en: 'Veterinary assistant', am: 'የእንስሳት ህክምና ረዳት (Yeensisat Hikmina Redat)', om: 'Gargaaraa Yaala Beeyiladaa', t: 'FG' },
    ],
  },
  {
    key: 'education_training', en: 'Education & Training', am: 'ትምህርትና ስልጠና', om: 'Barnoota fi Leenjii', icon: 'graduation-cap', vertical: 'pro', bandLow: 200, bandHigh: 5000,
    roles: [
      { k: 'primary_teacher', en: 'Primary school teacher', am: 'የአንደኛ ደረጃ መምህር (Yeandegna Dereja Memihir)', om: 'Barsiisaa Sadarkaa Tokkoffaa', t: 'F' },
      { k: 'secondary_teacher', en: 'Secondary school teacher', am: 'የሁለተኛ ደረጃ መምህር (Yehuletegna Dereja Memihir)', om: 'Barsiisaa Sadarkaa Lammaffaa', t: 'F' },
      { k: 'lecturer', en: 'University lecturer', am: 'የዩኒቨርሲቲ መምህር (Yeuniversity Memihir)', om: 'Lektshara / Barsiisaa Yuunivarsiitii', t: 'F' },
      { k: 'private_tutor', en: 'Private tutor — academic', am: 'የግል የቤት መምህር (Yegil Yebet Memihir)', om: 'Barsiisaa Dhuunfaa Manaa', t: 'GS' },
      { k: 'language_tutor', en: 'Language tutor', am: 'የቋንቋ መምህር (Yequanqua Memihir)', om: 'Barsiisaa Afaanii', t: 'GS' },
      { k: 'exam_coach', en: 'Exam prep coach', am: 'የፈተና ዝግጅት አሰልጣኝ (Yefetena Zigijit Aseltagn)', om: 'Leenjisaa Qophii Qorumsaa', t: 'GS' },
      { k: 'kindergarten', en: 'Early childhood / kindergarten teacher', am: 'የህጻናት መዋያ/ኪንደርጋርተን መምህር (Yehitsanat Mewaya Memihir)', om: 'Barsiisaa Kilasii Ijoollee (Kindergaartinii)', t: 'FI' },
      { k: 'special_ed', en: 'Special education teacher', am: 'የልዩ ፍላጎት መምህር (Yeliyu Filagot Memihir)', om: 'Barsiisaa Fedhii Addaa', t: 'F' },
      { k: 'tvet_instructor', en: 'Vocational/TVET instructor', am: 'የሙያና ቴክኒክ (TVET) አሰልጣኝ (Yemuya-na Technic Aseltagn)', om: 'Leenjisaa Kolleejjii Tiiviitii (TVET)', t: 'FG' },
      { k: 'music_teacher', en: 'Music teacher', am: 'የሙዚቃ መምህር (Yemusika Memihir)', om: 'Barsiisaa Sirbaa fi Muuziqaanii', t: 'GS' },
      { k: 'driving_instructor', en: 'Driving instructor', am: 'የመኪና አሽከርካሪነት አሰልጣኝ (Yemekina Ashkerkarinet Aseltagn)', om: 'Leenjisaa Konkolaachisummaa', t: 'FG' },
      { k: 'it_trainer', en: 'Computer/IT skills trainer', am: 'የኮምፒውተርና አይቲ ባለሙያ አሰልጣኝ (Yecomputer IT Aseltagn)', om: 'Leenjisaa Beekumsa Kompiutaraa', t: 'FGS' },
      { k: 'religious_teacher', en: 'Quran / religious teacher', am: 'የሃይማኖት መምህር (Yehaymanot Memihir)', om: 'Barsiisaa Amantii (Qeesii/Ustaazii)', t: 'IGS' },
      { k: 'teaching_assistant', en: 'Teaching assistant', am: 'ረዳት መምህር (Redat Memihir)', om: 'Gargaaraa Barsiisaa', t: 'FS' },
    ],
  },
  {
    key: 'office_admin', en: 'Office, Admin & Business Support', am: 'ቢሮ፣ አስተዳደርና ድጋፍ', om: 'Waajira, Bulchiinsa fi Deeggarsa', icon: 'briefcase', vertical: 'pro', bandLow: 200, bandHigh: 4000,
    roles: [
      { k: 'receptionist', en: 'Receptionist / front desk', am: 'እንግዳ ተቀባይ (Ingida Teqebay)', om: 'Simattu Waajiraa (Resepshiniistii)', t: 'FS' },
      { k: 'admin_assistant', en: 'Administrative assistant', am: 'የአስተዳደር ረዳት (Yeastedader Redat)', om: 'Gargaaraa Bulchiinsaa', t: 'F' },
      { k: 'data_entry', en: 'Data entry clerk', am: 'የመረጃ መዝጋቢ ሰራተኛ (Yemereja Mezgabi Serategna)', om: 'Galmeessituu Daataa', t: 'FGS' },
      { k: 'secretary', en: 'Secretary / executive assistant', am: 'ጸሐፊ / ዋና ረዳት (Tsehafi / Wana Redat)', om: 'Barreessituu Waajiraa', t: 'F' },
      { k: 'office_messenger', en: 'Office messenger / runner', am: 'የቢሮ መልዕክተኛ (Yebiro Mel\'ektegna)', om: 'Ergaa Waajiraa (Milaaktegnaa)', t: 'IF' },
      { k: 'bookkeeper', en: 'Bookkeeper', am: 'የሂሳብ መዛግብት ያዥ (Yehisab Mezagibt Yazh)', om: 'Galmeessituu Herregaa', t: 'FG' },
      { k: 'accountant', en: 'Accountant', am: 'የሂሳብ ባለሙያ (Yehisab Balemuya)', om: 'Ogeessa Herregaa (Akawauntantii)', t: 'F' },
      { k: 'auditor', en: 'Auditor', am: 'የሂሳብ ተቆጣጣሪ / ኦዲተር (Yehisab Teqotatari / Auditor)', om: 'Oditarii / To\'ataa Herregaa', t: 'F' },
      { k: 'hr_officer', en: 'HR officer', am: 'የሰው ሀብት አስተዳደር ባለሙያ (Yesew Habt Astedader Balemuya)', om: 'Ogeessa Qabeenya Namaa (HR)', t: 'F' },
      { k: 'office_manager', en: 'Office manager', am: 'የቢሮ ስራ አስኪያጅ (Yebiro Sira Askiyaj)', om: 'Hoogganaa Waajiraa', t: 'F' },
      { k: 'procurement', en: 'Procurement officer', am: 'የግዢ ባለሙያ (Yegizi Balemuya)', om: 'Ogeessa Bittaa Meeshaa', t: 'F' },
      { k: 'customer_service', en: 'Customer service representative', am: 'የደንበኞች አገልግሎት ሰራተኛ (Yedenbegnoch Agelglot Serategna)', om: 'Tajaajiltuu Maamiltootaa', t: 'FS' },
      { k: 'call_center', en: 'Call center agent', am: 'የጥሪ ማዕከል ሰራተኛ (Yetiri Ma\'ikel Serategna)', om: 'Hojjattuu Waajira Bilbilaa', t: 'FS' },
      { k: 'virtual_assistant', en: 'Virtual assistant (remote)', am: 'በይነመረብ ረዳት ሰራተኛ (Beynemereb Redat Serategna)', om: 'Gargaaraa Interneetiin Hojjetu', t: 'GS' },
      { k: 'translator', en: 'Translator / interpreter', am: 'አስተርጓሚ (Astergwami)', om: 'Hiiktuu Afaanii (Turjumaana)', t: 'FGS' },
      { k: 'transcriptionist', en: 'Transcriptionist', am: 'ድምፅ ወደ ጽሑፍ ቀያሪ (Dimts wede Tsehuf Qeyari)', om: 'Sagalee gara Barruutti Hiiktuu', t: 'GS' },
      { k: 'digitization', en: 'Document scanning/digitization', am: 'ሰነድ ዲጂታይዝ አድራጊ (Sened Digitise Adragi)', om: 'Kompiutaratti Galmeessituu Senedaa', t: 'GS' },
    ],
  },
  {
    key: 'finance_banking', en: 'Finance, Banking & Microfinance', am: 'ፋይናንስ፣ ባንክና ጥቃቅን ብድር', om: 'Faayinaansii, Baankii fi Maayikiroofaayinaansii', icon: 'banknote', vertical: 'pro', bandLow: 300, bandHigh: 5000,
    roles: [
      { k: 'bank_teller', en: 'Bank teller', am: 'የባንክ ገንዘብ ተቀባይ/ከፋይ (Yebank Genzeb Teqebay/Kefay)', om: 'Tellerii Baankii', t: 'F' },
      { k: 'loan_officer', en: 'Loan officer', am: 'የብድር ባለሙያ (Yebidir Balemuya)', om: 'Ogeessa Liqii Baankii', t: 'F' },
      { k: 'mfi_field', en: 'Microfinance field officer', am: 'የጥቃቅንና አነስተኛ ብድር የመስክ ሰራተኛ (Yetiqaqinna Anestegna Bidir Yemesk Serategna)', om: 'Hojjetaa Dirree Maayikiroo-Fayinaansii', t: 'FG' },
      { k: 'credit_analyst', en: 'Credit analyst', am: 'የብድር ተንታኝ ባለሙያ (Yebidir Tentagn Balemuya)', om: 'Ogeessa Xiinxala Liqii', t: 'F' },
      { k: 'insurance_agent', en: 'Insurance agent', am: 'የኢንሹራንስ ወኪል (Yeinsurance Wekil)', om: 'Bakka-bu\'aa Inshuraansii', t: 'FG' },
      { k: 'financial_advisor', en: 'Financial advisor', am: 'የፋይናንስ አማካሪ (Yefinance Amakari)', om: 'Gorsa Qabeenyaa/Fayinaansii', t: 'FG' },
      { k: 'tax_preparer', en: 'Tax preparer / consultant', am: 'የግብር አማካሪ (Yegibir Amakari)', om: 'Gorsa Gibiraa/Taaksii', t: 'FGS' },
      { k: 'equb_edir', en: 'Equb/Edir collector & coordinator', am: 'የእቁብ/ዕድር ሰብሳቢና አስተባባሪ (Yeequb/Yeedir Sabsabi-na Astebabari)', om: 'Qindeessituu Iqubii fi Iddirii', t: 'IS' },
      { k: 'bank_cashier', en: 'Cashier (bank/MFI)', am: 'የባንክ ካሺየር (Yebank Cashier)', om: 'Kashiyeerii Baankii', t: 'F' },
    ],
  },
  {
    key: 'technology_digital', en: 'Technology & Digital', am: 'ቴክኖሎጂና ዲጂታል', om: 'Teknooloojii fi Dijitaalaa', icon: 'monitor', vertical: 'pro', bandLow: 500, bandHigh: 15000,
    roles: [
      { k: 'software_dev', en: 'Software developer', am: 'የሶፍትዌር አልሚ (Yesoftware Almi)', om: 'Misoomsituu Softiweerii', t: 'FG' },
      { k: 'mobile_dev', en: 'Mobile app developer', am: 'የሞባይል መተግበሪያ አልሚ (Yemobile Metigberiya Almi)', om: 'Misoomsituu Appilikeeshinii Moobaayilii', t: 'FG' },
      { k: 'web_dev', en: 'Web developer', am: 'የድረ-ገጽ አልሚ (Yedre-gets Almi)', om: 'Misoomsituu Weebsaayitii', t: 'FGS' },
      { k: 'ui_ux', en: 'UI/UX designer', am: 'የተጠቃሚ በይነገጽ ዲዛይነር (Yetetteqami Beynegets Designer)', om: 'Diizaayinii Mul\'ata Appilikeeshinii (UI/UX)', t: 'FG' },
      { k: 'data_analyst', en: 'Data analyst', am: 'የመረጃ ተንታኝ (Yemereja Tentagn)', om: 'Xiinxaltuu Daataa', t: 'FG' },
      { k: 'it_support', en: 'IT support technician', am: 'የአይቲ ረዳት ቴክኒሻን (Ye-IT Redat Technician)', om: 'Teekinishiana Gargaarsa IT', t: 'FGS' },
      { k: 'network_admin', en: 'Network administrator', am: 'የኔትወርክ አስተዳዳሪ (Yenetwork Astedaderi)', om: 'Bulchitoota Neetworkii', t: 'F' },
      { k: 'dba', en: 'Database administrator', am: 'የመረጃ ቋት አስተዳዳሪ (Yemereja Quat Astedaderi)', om: 'Bulchitoota Daataabeesii', t: 'F' },
      { k: 'qa_tester', en: 'QA / software tester', am: 'የሶፍትዌር ጥራት ተቆጣጣሪ (Yesoftware Tsirat Teqotatari)', om: 'To\'attuu Qulqullina Softiweerii', t: 'FGS' },
      { k: 'devops', en: 'DevOps engineer', am: 'የዴቭኦፕስ መሃንዲስ (YeDevOps Mehandis)', om: 'Injinshara Deev-Opsii (DevOps)', t: 'F' },
      { k: 'cybersec', en: 'Cybersecurity analyst', am: 'የሳይበር ደህንነት ተንታኝ (Yecyber Dehninet Tentagn)', om: 'Xiinxaltuu Nageenya Saayiberii', t: 'F' },
      { k: 'sys_analyst', en: 'Systems analyst', am: 'የሲስተም ተንታኝ (Yesystem Tentagn)', om: 'Xiinxaltuu Sirna Kompiutaraa', t: 'F' },
      { k: 'tech_support_remote', en: 'Tech support (remote)', am: 'የርቀት የቴክኒክ ድጋፍ ሰጪ (Yeruq Yetechnic Digaf Sechi)', om: 'Gargaarsa Teekinikaa Fagoo', t: 'GS' },
      { k: 'nocode_builder', en: 'No-code / automation builder', am: 'የኖ-ኮድ/ራስ-ሰር ሲስተም አልሚ (Ye-no-code System Almi)', om: 'Misoomsituu Sirna Noo-Koodii', t: 'GS' },
    ],
  },
  {
    key: 'creative_media', en: 'Creative, Media & Marketing', am: 'ፈጠራ፣ ሚዲያና ግብይት', om: 'Aartii, Miidiyaa fi Maarkeetingii', icon: 'palette', vertical: 'pro', bandLow: 300, bandHigh: 8000,
    roles: [
      { k: 'graphic_designer', en: 'Graphic designer', am: 'ግራፊክ ዲዛይነር (Graphic Designer)', om: 'Diizaayinii Giraafiksii', t: 'FGS' },
      { k: 'photographer', en: 'Photographer', am: 'ፎቶግራፍ አንሺ (Photograph Anshi)', om: 'Kaastuu Footoo', t: 'FGS' },
      { k: 'videographer', en: 'Videographer', am: 'ቪዲዮ ቀራጭ (Video Qerach)', om: 'Waraabduu Viidiyoo', t: 'GS' },
      { k: 'video_editor', en: 'Video editor', am: 'ቪዲዮ አቀናባሪ (Video Aqenabari)', om: 'Qindeessituu Viidiyoo', t: 'GS' },
      { k: 'photo_retoucher', en: 'Photo retoucher', am: 'ፎቶ አቀናባሪ (Photo Aqenabari)', om: 'Qindeessituu Footoo', t: 'GS' },
      { k: 'social_media', en: 'Social media manager', am: 'የማህበራዊ ሚዲያ አስተዳዳሪ (Yemahberawi Media Astedaderi)', om: 'Bulchituu Miidiyaa Hawaasaa', t: 'FGS' },
      { k: 'content_writer', en: 'Content writer / copywriter', am: 'የጽሑፍ ይዘት አዘጋጅ (Yetsehhuf Yizet Azegaj)', om: 'Barreessituu Qabiyyee', t: 'GS' },
      { k: 'journalist', en: 'Blogger / journalist', am: 'ብሎገር / ጋዜጠኛ (Blogger / Gazetegna)', om: 'Gaazeexessituu / Bloggerii', t: 'FG' },
      { k: 'voiceover', en: 'Voice-over artist', am: 'የድምፅ ተዋናይ (Yedimts Tewanay)', om: 'Hojjattuu Sagalee Beeksisaa', t: 'GS' },
      { k: 'animator', en: 'Animator / motion designer', am: 'አኒሜተር / ተንቀሳቃሽ ምስል ዲዛይነር (Animator Designer)', om: 'Diizaayinii Sosso\'aa (Animeeshinii)', t: 'GS' },
      { k: 'illustrator', en: 'Illustrator', am: 'ሰዓሊ / ስዕላዊ መግለጫ ሰሪ (Se\'ali / S\'ilawi Meglecha Seriy)', om: 'Fakkibarreessituu', t: 'GS' },
      { k: 'brand_designer', en: 'Brand / logo designer', am: 'የብራንድና ሎጎ ዲዛይነር (Yebrand-na Logo Designer)', om: 'Diizaayinii Loogoo fi Beeksisaa', t: 'GS' },
      { k: 'digital_marketer', en: 'Digital marketer / SEO specialist', am: 'የዲጂታል ማርኬቲንግ ባለሙያ (Yedigital Marketing Balemuya)', om: 'Ogeessa Beeksisa Diijitaalaa (SEO)', t: 'FGS' },
      { k: 'event_photographer', en: 'Event photographer (weddings)', am: 'የሰርግ ፎቶግራፍ አንሺ (Yeserg Photograph Anshi)', om: 'Waraabduu Cidhaa', t: 'GS' },
      { k: 'drone_op', en: 'Drone operator', am: 'የድሮን አንቀሳቃሽ (Yedrone Anqesaqash)', om: 'Opreitara Diroonii', t: 'GS' },
      { k: 'print_op', en: 'Print/press operator', am: 'የህትመት ማሽን አንቀሳቃሽ (Yehitmet Machine Anqesaqash)', om: 'Opreitara Mashinii Maxxansaa', t: 'FI' },
      { k: 'signage_maker', en: 'Signage & banner maker', am: 'የማስታወቂያ ቦርድና ባነር ሰሪ (Yemastawodiya Board-na Banner Seriy)', om: 'Tolchituu Baanarii fi Boordii Beeksisaa', t: 'IG' },
    ],
  },
  {
    key: 'events_arts', en: 'Events, Arts & Entertainment', am: 'ዝግጅት፣ ጥበብና መዝናኛ', om: 'Sagantaalee, Aartii fi Bashannana', icon: 'music', vertical: 'pro', bandLow: 300, bandHigh: 8000,
    roles: [
      { k: 'event_planner', en: 'Event planner / coordinator', am: 'የዝግጅት አቀናባሪ / አስተባባሪ (Yezigijit Aqenabari / Astebabari)', om: 'Qindeessituu Sagantaalee', t: 'FG' },
      { k: 'wedding_planner', en: 'Wedding planner', am: 'የሰርግ ዝግጅት አቀናባሪ (Yeserg Zigijit Aqenabari)', om: 'Qindeessituu Cidhaa', t: 'GS' },
      { k: 'mc_host', en: 'MC / host', am: 'መድረክ መሪ / አስተናጋጅ (Medrek Meri / Astenagaj)', om: 'Hogganaa Sagantaa / Shaashituu (MC)', t: 'GS' },
      { k: 'dj', en: 'DJ', am: 'ዲጄ / የሙዚቃ አቀናባሪ (DJ / Yemusika Aqenabari)', om: 'Diijee (DJ) Muuziqaanii', t: 'GS' },
      { k: 'live_band', en: 'Live musician / band', am: 'የቀጥታ ሙዚቀኛ / ባንድ (Yeqetta Muziqegna / Band)', om: 'Muuziqaanii Sirna-Gulaa (Live Band)', t: 'GS' },
      { k: 'traditional_dancer', en: 'Traditional dancer / performer', am: 'የባህል ዳንሰኛ / እስክስታ ገራፊ (Yebahal Dansigna / Eskesta Gerafi)', om: 'Shifftuu/Sirbituu Aadaa', t: 'GS' },
      { k: 'sound_light', en: 'Sound & lighting technician', am: 'የድምፅና መብራት ቴክኒሻን (Yedimts-na Mebrat Technician)', om: 'Teekinishiana Sagalee fi Ifaa', t: 'GS' },
      { k: 'stage_tent', en: 'Stage & tent setup crew', am: 'የመድረክና ድንኳን ገጣሚ (Yemedrek-na Dinkuan Getami)', om: 'Naqtuu Dasiigi fi Dunkaanaa', t: 'IS' },
      { k: 'decorator', en: 'Decorator / florist', am: 'የዝግጅት ቦታ አልሺ / ዲኮሬተር (Yezigijit Bota Alachi / Decorator)', om: 'Bareessituu Sagantaalee / Abaaboo', t: 'GS' },
      { k: 'usher', en: 'Usher / crowd steward', am: 'አሸኛኝ / የእንግዳ መሪ (Ashegnagn / Yeingida Meri)', om: 'Simattuu fi Karaa-agarsiistuu (Asherii)', t: 'GS' },
      { k: 'actor_extra', en: 'Actor / extra', am: 'ተዋናይ / ረዳት ተዋናይ (Tewanay / Redat Tewanay)', om: 'Tabattuu Fiilmii', t: 'GS' },
      { k: 'kids_entertainer', en: 'Face painter / kids entertainer', am: 'የህጻናት መዝናኛና ፊት ቀቢ (Yehitsanat Meznagnana Fit Qebiy)', om: 'Taphachiistuu fi Miidhassituu Ijoollee', t: 'GS' },
    ],
  },
  {
    key: 'agriculture_rural', en: 'Agriculture & Rural', am: 'ግብርናና ገጠር', om: 'Qonnaa fi Baadiyyaa', icon: 'sprout', vertical: 'home', bandLow: 150, bandHigh: 2000,
    roles: [
      { k: 'farm_laborer', en: 'Farm laborer (daily)', am: 'የቀን ግብርና ሰራተኛ (Yeqen Gibrina Serategna)', om: 'Hojjetaa Guyyaa Qonnaa', t: 'IS' },
      { k: 'harvest_worker', en: 'Harvest worker (seasonal)', am: 'የሰብል ሰብሳቢ / አጫጅ (Yesebil Sabsabi / Achaj)', om: 'Sassaabduu Midhaanii', t: 'IS' },
      { k: 'coffee_picker', en: 'Coffee picker', am: 'የቡና ለቃሚ (Yebunna Leqami)', om: 'Guurtuu Bunaa', t: 'IS' },
      { k: 'herder', en: 'Livestock herder', am: 'እረኛ (Eregna)', om: 'Tiksee Loonii', t: 'I' },
      { k: 'dairy_worker', en: 'Dairy farm worker', am: 'የወተት እርባታ ሰራተኛ (Yewotet Irbata Serategna)', om: 'Hojjetaa Qonnaa Aananii', t: 'IF' },
      { k: 'poultry_worker', en: 'Poultry farm worker', am: 'የዶሮ እርባታ ሰራተኛ (Yedoro Irbata Serategna)', om: 'Hojjetaa Qonnaa Lukkuu', t: 'IF' },
      { k: 'beekeeper', en: 'Beekeeper', am: 'የንብ እርባታ ባለሙያ (Yenib Irbata Balemuya)', om: 'Kunuunsituu Kanniisaa', t: 'IG' },
      { k: 'irrigation_tech', en: 'Irrigation technician', am: 'የመስኖ ቴክኒሻን (Yemesno Technician)', om: 'Teekinishiana Jallisi Qonnaa', t: 'FG' },
      { k: 'agronomist', en: 'Agronomist / extension agent', am: 'የግብርና ኤክስቴንሽን ባለሙያ (Yegibrina Extension Balemuya)', om: 'Ogeessa Eksiteenshinii Qonnaa', t: 'FG' },
      { k: 'greenhouse_worker', en: 'Greenhouse worker', am: 'የግሪን ሃውስ/የአበባ እርሻ ሰራተኛ (Yegreenhouse Irsha Serategna)', om: 'Hojjetaa Mana Saphanaa (Greenhouse)', t: 'IF' },
      { k: 'vet_field', en: 'Veterinary field worker', am: 'የመስክ እንስሳት ህክምና ረዳት (Yemesk Ensisat Hikmina Redat)', om: 'Hojjetaa Dirree Yaala Beeyiladaa', t: 'FG' },
      { k: 'grain_mill', en: 'Grain mill operator', am: 'የወፍጮ ቤት ሰራተኛ (Yewofcho Bet Serategna)', om: 'Opreitara Daakuu Midhaanii', t: 'I' },
    ],
  },
  {
    key: 'security_facilities', en: 'Security & Facilities', am: 'ደህንነትና ተቋማት', om: 'Nageenya fi Dhaabbilee', icon: 'shield', vertical: 'home', bandLow: 200, bandHigh: 2500,
    roles: [
      { k: 'security_guard', en: 'Security guard', am: 'የጥበቃ ሰራተኛ / ዘበኛ (Yetibeqqa Serategna / Zebegna)', om: 'Eegduu Nageenyaa (Zebegnaa)', t: 'FI' },
      { k: 'night_watchman', en: 'Night watchman', am: 'የሌሊት ጥበቃ ሰራተኛ (Yelelit Tibeqqa Serategna)', om: 'Tiksee Halkanii', t: 'IS' },
      { k: 'gatekeeper', en: 'Gatekeeper / doorman', am: 'የበር ጠባቂ (Yeber Tabaqi)', om: 'Eegduu Karra Manaa', t: 'IF' },
      { k: 'janitor', en: 'Building caretaker / janitor', am: 'የህንፃ ተንከባካቢ (Yehintsa Tenkebakabi)', om: 'Tiksee/Kunuunsituu Gamoo', t: 'FI' },
      { k: 'facilities_maint', en: 'Facilities maintenance worker', am: 'የህንፃ ጥገናና መገልገያ ሰራተኛ (Yehintsa Tgenana Megelgeya Serategna)', om: 'Hojjetaa Suphaa Meeshaalee Gamoo', t: 'F' },
      { k: 'parking_attendant', en: 'Parking attendant', am: 'የመኪና ማቆሚያ ተላላኪ (Yemekina Maqomiya Telalaki)', om: 'Tiksee Idoo Dhaabbata Konkolaataa', t: 'IS' },
      { k: 'fire_safety', en: 'Fire safety officer', am: 'የእሳት አደጋ መከላከያ ባለሙያ (Yeeat Adega Mekelekeya Balemuya)', om: 'Ogeessa Ittisa Balaa Abiddaa', t: 'F' },
      { k: 'event_security', en: 'Crowd control / event security', am: 'የዝግጅት ደህንነት ጠባቂ / ባውንሰር (Yezigijit Dehninet Tabaqi / Bouncer)', om: 'Tiksee Nageenya Sagantaalee (Baawunserii)', t: 'GS' },
    ],
  },
  {
    key: 'professional_consulting', en: 'Professional & Consulting', am: 'ሙያዊና አማካሪ', om: 'Ogummaa fi Gorsaa', icon: 'scale', vertical: 'pro', bandLow: 500, bandHigh: 15000,
    roles: [
      { k: 'lawyer', en: 'Lawyer / legal advisor', am: 'ጠበቃ / የህግ አማካሪ (Tebeqa / Yehig Amakari)', om: 'Abukaatoo / Gorsa Seeraa', t: 'FG' },
      { k: 'paralegal', en: 'Paralegal / legal assistant', am: 'ረዳት ጠበቃ (Redat Tebeqa)', om: 'Gargaaraa Abukaatoo', t: 'FG' },
      { k: 'architect', en: 'Architect', am: 'አርክቴክት (Architect)', om: 'Diizaayinii Gamoo (Arkiteektii)', t: 'FG' },
      { k: 'civil_engineer', en: 'Civil engineer', am: 'ሲቪል መሃንዲስ (Civil Mehandis)', om: 'Injinshara Siivilii', t: 'FG' },
      { k: 'mechanical_engineer', en: 'Mechanical engineer', am: 'መካኒካል መሃንዲስ (Mechanical Mehandis)', om: 'Injinshara Mekaanikalii', t: 'F' },
      { k: 'electrical_engineer', en: 'Electrical engineer', am: 'ኤሌክትሪካል መሃንዲስ (Electrical Mehandis)', om: 'Injinshara Elektiriikalii', t: 'F' },
      { k: 'project_manager', en: 'Project manager', am: 'የፕሮጀክት ስራ አስኪያጅ (Yeproject Sira Askiyaj)', om: 'Hoogganaa Piroojektii', t: 'FG' },
      { k: 'business_consultant', en: 'Business consultant', am: 'የንግድ ስራ አማካሪ (Yenigd Sira Amakari)', om: 'Gorsa Daldaala/Bizinesii', t: 'FG' },
      { k: 'market_researcher', en: 'Market researcher / enumerator', am: 'የመረጃ ሰብሳቢ / ቆጣሪ (Yemereja Sabsabi / Qotari)', om: 'Sassaabduu Ragaa Gabaa', t: 'GS' },
      { k: 'real_estate', en: 'Real estate agent / broker (Delala)', am: 'የሪል ስቴት ወኪል / ደላላ (Ye Real Estate Wekil / Delala)', om: 'Bakka-bu\'aa Qabeenya Dhaabbataa / Dilaalaa', t: 'FG' },
      { k: 'property_manager', en: 'Property manager', am: 'የንብረት አስተዳዳሪ (Yenibret Astedaderi)', om: 'Bulchituu Qabeenyaa', t: 'F' },
      { k: 'quantity_surveyor', en: 'Quantity surveyor', am: 'የግንባታ ወጪ ተንታኝ (Yeginbata Wechi Tentagn)', om: 'Lekeessaa fi Xiinxaltuu Gatii Ijaarsaa', t: 'FG' },
    ],
  },
  {
    key: 'micro_gigs', en: 'Micro-gigs & Errands', am: 'አነስተኛ ስራዎችና መልዕክቶች', om: 'Hojiiwwan Xixiqqaa fi Ergaa', icon: 'shopping-bag', vertical: 'delivery', bandLow: 80, bandHigh: 600,
    roles: [
      { k: 'queue_standing', en: 'Queue-standing / line waiting', am: 'ወረፋ ጠባቂ ሰራተኛ (Werefa Tabaqi Serategna)', om: 'Eegduu Tarree (Werefaa)', t: 'GS' },
      { k: 'errand_runner', en: 'Errand runner', am: 'ጉዳይ አስፈጻሚ ተላላኪ (Guday Asfetsami Telalaki)', om: 'Ergamtuu Dhimmootaa', t: 'GS' },
      { k: 'bill_runner', en: 'Bill payment & paperwork runner', am: 'የክፍያና ሰነድ ጉዳይ አስፈጻሚ (Yekefiyana Sened Guday Asfetsami)', om: 'Raawwachiistuu Kafaltii fi Senedaa', t: 'IS' },
      { k: 'mystery_shopper', en: 'Mystery shopper', am: 'ሚስጥራዊ የገዢ ተመልካች (Mistirawi Yegezi Temelkachi)', om: 'Bitattuu Iccitii To\'attu', t: 'GS' },
      { k: 'survey_respondent', en: 'Survey respondent / focus group', am: 'የዳሰሳ ጥናት ምላሽ ሰጪ (Yedasesa Tnat Milash Sechi)', om: 'Deebistuu Qorannoo', t: 'GS' },
      { k: 'flyer_distribution', en: 'Flyer distribution', am: 'የማስታወቂያ ወረቀት አከፋፋይ (Yemastawodiya Wereqet Akefafay)', om: 'Raabsituu Waraqaa Beeksisaa', t: 'IS' },
      { k: 'poster_painting', en: 'Poster & wall painting (ads)', am: 'የማስታወቂያ ግድግዳ ቀለም ቀቢ (Yemastawodiya Gidgida Qelem Qebiy)', om: 'Dibduu Beeksisa Gidgidaa', t: 'IS' },
      { k: 'flatpack_assembly', en: 'Assembly (flat-pack furniture)', am: 'የቤት ዕቃዎች ገጣሚ (Yebet Eqaoch Getami)', om: 'Naqtuu Meeshaa Manaa (Flat-pack)', t: 'GS' },
      { k: 'yard_clearing', en: 'Yard clearing (seasonal)', am: 'የግቢ ማጽጃና ማሳመሪያ (Yegibi Matsjana Masameriya)', om: 'Qulqulleessituu fi Bareessituu Keessoo Mooraa', t: 'IS' },
      { k: 'popup_staff', en: 'Pop-up shop staff', am: 'የጊዚያዊ አውደ-ርዕይ ሰራተኛ (Yegiziyawi Awde-ri\'iy Serategna)', om: 'Hojjattuu Baazaarii/Gabaa Yeroo', t: 'GS' },
    ],
  },
];

// Flatten roles for search / CV matching
export const ALL_ROLES = TAXONOMY.flatMap((g) =>
  g.roles.map((r) => ({ ...r, group: g.key, groupEn: g.en })),
);

export function taxonomyCategories() {
  return TAXONOMY.map((g) => ({
    key: g.key,
    en: g.en,
    am: g.am,
    om: g.om,
    icon: g.icon,
    vertical: g.vertical,
    bandLow: g.bandLow,
    bandHigh: g.bandHigh,
    roleCount: g.roles.length,
  }));
}

export const TAX_CATEGORY_KEYS = TAXONOMY.map((g) => g.key);
